# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ku1+wigLI8neo/kIMhbh+C+EnqJUfnnridCHKCRu3CHxU2nI2j4BVlmZcaoUVKcTeszGUZxz3qbouNP1y0ncbQHOv6wANuQbIulujtfxdVnt0mcGKfHe2EH/4BVCvvkLh29Cd2N4wSDDHUPlqo8rpttsJBjWpwT0u9/Yllwp7jkV+2mqtm6nhif1oX2kqJFz/A8E17iraQ3K/rQP+d0GmslImLWKEk9Ucl0KkMZX1fwRsUjJq6N85skP8VGcIsIardVBGIzNIWzn85hnhasyLvuZvaqX6tj5iub/LrbaI6CDmw83RVcy42pW4HCmJtytHLL5/9BDXxerYZNv5/pO/nYPYu/IAHtRPzbul+6PBU4V4qAzs2cfPBGlHLCiLUSLxjNsk2Ac6ip341OIwv2jj9MGxbe0YYrJQCUslHcUr/NRUzwdywl2UdCM95OtTVeyZSdKQSqYB4vM1Vf3MMjn4O33rKt1RfEC1zfYf19nCaKVdH91sMTM2yumviU121eM5zXwbDTaB3kkAKIIDcJifhO5JGeaZYjm4abTjRDkN1ETjjHQZlFBOpvHUDKtyvnsVYZP+WYGWBsWu+QHofdxKSLFOkatPQbY7AXxmV3HBZdT7ai6podpREDaXIK8jeIMyg+Qb6WSt29XDnfHJzwQukMWFCjE6OEts7HntqiKuYI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
