travis:
  secure:
    BINSTAR_TOKEN: ku1+wigLI8neo/kIMhbh+C+EnqJUfnnridCHKCRu3CHxU2nI2j4BVlmZcaoUVKcTeszGUZxz3qbouNP1y0ncbQHOv6wANuQbIulujtfxdVnt0mcGKfHe2EH/4BVCvvkLh29Cd2N4wSDDHUPlqo8rpttsJBjWpwT0u9/Yllwp7jkV+2mqtm6nhif1oX2kqJFz/A8E17iraQ3K/rQP+d0GmslImLWKEk9Ucl0KkMZX1fwRsUjJq6N85skP8VGcIsIardVBGIzNIWzn85hnhasyLvuZvaqX6tj5iub/LrbaI6CDmw83RVcy42pW4HCmJtytHLL5/9BDXxerYZNv5/pO/nYPYu/IAHtRPzbul+6PBU4V4qAzs2cfPBGlHLCiLUSLxjNsk2Ac6ip341OIwv2jj9MGxbe0YYrJQCUslHcUr/NRUzwdywl2UdCM95OtTVeyZSdKQSqYB4vM1Vf3MMjn4O33rKt1RfEC1zfYf19nCaKVdH91sMTM2yumviU121eM5zXwbDTaB3kkAKIIDcJifhO5JGeaZYjm4abTjRDkN1ETjjHQZlFBOpvHUDKtyvnsVYZP+WYGWBsWu+QHofdxKSLFOkatPQbY7AXxmV3HBZdT7ai6podpREDaXIK8jeIMyg+Qb6WSt29XDnfHJzwQukMWFCjE6OEts7HntqiKuYI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
